export const NAME_CHANGE = 'NAME_CHANGE';

export const INCREASE_AUTHOR = 'INCREASE_AUTHOR';

export const DECREASE_AUTHOR = 'DECREASE_AUTHOR';

export const TITLE_CHANGE = 'TITLE_CHANGE';

export const DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE';

export const DURATION_CHANGE = 'DURATION_CHANGE';
